import { Template } from 'e2b'

export const mailTemplate = Template()
  .fromImage('e2bdev/code-interpreter:latest')
  .setUser('root')
  .setWorkdir('/')
  .runCmd('apt-get update && apt-get install -y git curl build-essential && rm -rf /var/lib/apt/lists/*')
  .runCmd('apt update && apt install -y gh')
  .runCmd('curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs')
  .runCmd('npm install -g pnpm')
  .setWorkdir('/home/user')
  .runCmd('echo v12')
  .runCmd('git clone -b mail --depth 1 https://github.com/kevin36524/hack-skeleton-app.git app')
  .runCmd('git clone -b main --depth 1 https://github.com/kevin36524/sandbox_utils.git sandbox_utils')
  .setWorkdir('/home/user/app')
  .runCmd('pnpm install')
  .runCmd('cp -r ../sandbox_utils/scripts scripts')
  .runCmd('mv ../sandbox_utils/.kimi ~/.kimi')
  .runCmd('curl -fsSL https://astral.sh/uv/install.sh | sh')
  .runCmd('source $HOME/.local/bin/env')
  .runCmd('curl -L code.kimi.com/install.sh | bash')
  .setUser('user')
  .setUser('user')
  .setWorkdir('/home/user')
