import { Template } from 'e2b'

export const mailTemplate = Template()
  .fromImage('e2bdev/code-interpreter:latest')
  .setUser('root')
  .setWorkdir('/')
  .runCmd('rm -f /etc/apt/sources.list.d/nodesource.list /usr/share/keyrings/nodesource.gpg 2>/dev/null || true')
  .runCmd('apt-get update && apt-get install -y git curl build-essential && rm -rf /var/lib/apt/lists/*')
  .runCmd('curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && apt-get update && apt-get install -y gh && rm -rf /var/lib/apt/lists/*')
  .runCmd('curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm install 22 && nvm use 22 && nvm alias default 22')
  .runCmd('export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" && npm install -g pnpm')
  .setWorkdir('/home/user')
  .runCmd('echo v18')
  .runCmd('git clone -b e2b/oath_gmail --depth 1 https://github.com/kevin36524/hack-skeleton-app.git app')
  .runCmd('git clone -b main --depth 1 https://github.com/kevin36524/sandbox_utils.git sandbox_utils')
  .setWorkdir('/home/user/app')
  .runCmd('pnpm install')
  .runCmd('cp -r ../sandbox_utils/scripts scripts')
  .runCmd('mv ../sandbox_utils/.kimi /home/user/.kimi')
  .setUser('user')
  .runCmd('curl -fsSL https://astral.sh/uv/install.sh | sh')
  .runCmd('source $HOME/.local/bin/env')
  .runCmd('curl -L code.kimi.com/install.sh | bash')
  .setUser('user')
  .setWorkdir('/home/user')
